# Generated by Django 5.1.3 on 2024-12-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_note_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.FileField(blank=True, default='default_images/img2.png', null=True, upload_to='user_folder'),
        ),
        migrations.AlterField(
            model_name='note',
            name='featured_image',
            field=models.FileField(blank=True, default='default_images/img2.png', null=True, upload_to='blog_img'),
        ),
    ]
