# Generated by Django 5.1.3 on 2024-12-11 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_customuser_image_alter_note_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('PROGRAMMING', 'Programming'), ('CLOUD', 'Cloud'), ('DEVOPS', 'Devops')], default='PROGRAMMING', max_length=15),
        ),
    ]
