
name: CI Pipeline for React and Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dockerize-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push React Image
        run: |
          docker build -t davidachoja/node-app:react-vite-app -f frontend/Dockerfile .
          docker push davidachoja/node-app:react-vite-app

  dockerize-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Django Image
        run: |
          docker build -t davidachoja/django-blog:latest -f backend/Dockerfile .
          docker push davidachoja/django-blog:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [dockerize-frontend, dockerize-backend]
    
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull davidachoja/node-app:react-vite-app
            docker pull davidachoja/django-blog:latest
            
            docker stop react-app || true
            docker stop django-app || true
            
            # Start React frontend container
            docker run -d -p 5173:5173 --name react-app  --restart unless-stopped  davidachoja/node-app:react-vite-app

            # Start Django backend container
            docker run -d -p 8000:8000 --name django-app  --restart unless-stopped  davidachoja/django-blog:latest
