name: CI Pipeline for React and Django

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Files to EC2
        uses: appleboy/scp-action@master
        with:
          source: "./"  # Copy everything in the repo
          target: "/home/ubuntu/uvyBlog"  # Destination folder on EC2
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd ~/uvyBlog

            # Install Node.js and NPM if not already installed
            if ! command -v node &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt install -y nodejs
            fi

            # Install Python and Pip if not installed
            if ! command -v python3 &> /dev/null; then
              sudo apt install -y python3 python3-pip
            fi
            
            # Update the .env file for React
            echo "VITE_API_URL=http://18.171.206.112:8000" > frontend/.env

            # Start React-vite frontend
            cd frontend
            npm install
            nohup npm run dev -- --host 0.0.0.0 > ~/frontend.log 2>&1 &

            # Start Django backend
            cd ../blog
            pip install -r requirements.txt
            nohup python3 manage.py runserver 0.0.0.0:8000 > ~/backend.log 2>&1 &
